service:
  name: serverless-to-do-api

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModels: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8080
      inMemory: true
      migrate: true  

functions:
  savetodo:
    handler: src/functions/saveTodo.handle
    events:
      - http:
          path: /todos/{userid}
          method: POST
          cors: true
  listtodo:
    handler: src/functions/listTodo.handle
    events:
      - http:
          path: /todos/{userid}
          method: GET
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH